import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { QrCode } from "lucide-react";
import { useState } from "react";

interface QRReportProps {
  healthScore: number;
  profileName: string;
}

export function QRReport({ healthScore, profileName }: QRReportProps) {
  const [open, setOpen] = useState(false);

  const reportText = `NutriScan Health Report\nName: ${profileName}\nScore: ${healthScore}/100\nDate: ${new Date().toLocaleDateString()}\nGenerated by NutriScan AI`;

  return (
    <div className="fixed bottom-6 right-6 z-50">
      <Dialog open={open} onOpenChange={setOpen}>
        <DialogTrigger asChild>
          <Button
            data-ocid="qr.open_modal_button"
            size="lg"
            className="rounded-full w-14 h-14 shadow-xl"
            style={{
              background: "oklch(75 0.18 170)",
              color: "oklch(15 0.02 220)",
            }}
          >
            <QrCode size={24} />
          </Button>
        </DialogTrigger>
        <DialogContent data-ocid="qr.dialog" className="max-w-sm">
          <DialogHeader>
            <DialogTitle>🏥 Health Report</DialogTitle>
          </DialogHeader>
          <div className="space-y-4">
            <div
              className="p-4 rounded-xl font-mono text-xs leading-relaxed whitespace-pre"
              style={{
                background: "oklch(22 0.03 220)",
                border: "1px solid oklch(28 0.025 220)",
              }}
            >
              {reportText}
            </div>
            <div
              className="flex items-center justify-center w-32 h-32 mx-auto rounded-xl"
              style={{
                background: "oklch(22 0.03 220)",
                border: "1px solid oklch(28 0.025 220)",
              }}
            >
              <div className="text-center">
                <QrCode size={64} className="text-foreground" />
                <p className="text-xs text-muted-foreground mt-1">QR Preview</p>
              </div>
            </div>
            <p className="text-xs text-center text-muted-foreground">
              Share this report with your doctor
            </p>
            <Button
              data-ocid="qr.close_button"
              variant="outline"
              className="w-full border-border"
              onClick={() => setOpen(false)}
            >
              Close
            </Button>
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
