/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ChatMessage = IDL.Record({
  'content' : IDL.Text,
  'role' : IDL.Text,
  'language' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const DoctorSuggestion = IDL.Record({
  'name' : IDL.Text,
  'available' : IDL.Bool,
  'specialty' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});
export const Vitamins = IDL.Record({
  'b12' : IDL.Nat,
  'iron' : IDL.Nat,
  'vitC' : IDL.Nat,
  'vitD' : IDL.Nat,
  'calcium' : IDL.Nat,
  'zinc' : IDL.Nat,
});
export const HealthEntry = IDL.Record({
  'mood' : IDL.Text,
  'notes' : IDL.Text,
  'timestamp' : IDL.Int,
  'healthScore' : IDL.Nat,
  'vitamins' : Vitamins,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'region' : IDL.Text,
  'weight' : IDL.Nat,
  'height' : IDL.Nat,
  'name' : IDL.Text,
  'language' : IDL.Text,
  'dietType' : IDL.Text,
});
export const AnalysisResult = IDL.Record({
  'moduleName' : IDL.Text,
  'explanation' : IDL.Text,
  'timestamp' : IDL.Int,
  'findings' : IDL.Vec(IDL.Text),
  'confidence' : IDL.Nat,
  'deficiencies' : IDL.Vec(IDL.Text),
});
export const MealItem = IDL.Record({
  'kcal' : IDL.Nat,
  'name' : IDL.Text,
  'nutrients' : IDL.Text,
});
export const DietPlan = IDL.Record({
  'date' : IDL.Int,
  'breakfast' : IDL.Vec(MealItem),
  'totalKcal' : IDL.Nat,
  'lunch' : IDL.Vec(MealItem),
  'snacks' : IDL.Vec(MealItem),
  'dinner' : IDL.Vec(MealItem),
});
export const GameStats = IDL.Record({
  'badges' : IDL.Vec(IDL.Text),
  'longestStreak' : IDL.Nat,
  'healthScore' : IDL.Nat,
  'lastCheckIn' : IDL.Int,
  'currentStreak' : IDL.Nat,
});
export const SunlightLog = IDL.Record({
  'date' : IDL.Int,
  'uvIndex' : IDL.Nat,
  'recommendation' : IDL.Text,
  'outdoorMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addChatMessage' : IDL.Func([ChatMessage], [], []),
  'addDoctorSuggestions' : IDL.Func([IDL.Vec(DoctorSuggestion)], [], []),
  'addHealthEntry' : IDL.Func([HealthEntry], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
  'getDietPlan' : IDL.Func([IDL.Int], [IDL.Opt(DietPlan)], ['query']),
  'getDoctorSuggestions' : IDL.Func([], [IDL.Vec(DoctorSuggestion)], ['query']),
  'getGameStats' : IDL.Func([], [IDL.Opt(GameStats)], ['query']),
  'getHealthTimeline' : IDL.Func([], [IDL.Vec(HealthEntry)], ['query']),
  'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
  'getSunlightHistory' : IDL.Func([], [IDL.Vec(SunlightLog)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'logSunlight' : IDL.Func([SunlightLog], [], []),
  'saveAnalysisResult' : IDL.Func([AnalysisResult], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveDietPlan' : IDL.Func([DietPlan], [], []),
  'updateGameStats' : IDL.Func([GameStats], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ChatMessage = IDL.Record({
    'content' : IDL.Text,
    'role' : IDL.Text,
    'language' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const DoctorSuggestion = IDL.Record({
    'name' : IDL.Text,
    'available' : IDL.Bool,
    'specialty' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  const Vitamins = IDL.Record({
    'b12' : IDL.Nat,
    'iron' : IDL.Nat,
    'vitC' : IDL.Nat,
    'vitD' : IDL.Nat,
    'calcium' : IDL.Nat,
    'zinc' : IDL.Nat,
  });
  const HealthEntry = IDL.Record({
    'mood' : IDL.Text,
    'notes' : IDL.Text,
    'timestamp' : IDL.Int,
    'healthScore' : IDL.Nat,
    'vitamins' : Vitamins,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'region' : IDL.Text,
    'weight' : IDL.Nat,
    'height' : IDL.Nat,
    'name' : IDL.Text,
    'language' : IDL.Text,
    'dietType' : IDL.Text,
  });
  const AnalysisResult = IDL.Record({
    'moduleName' : IDL.Text,
    'explanation' : IDL.Text,
    'timestamp' : IDL.Int,
    'findings' : IDL.Vec(IDL.Text),
    'confidence' : IDL.Nat,
    'deficiencies' : IDL.Vec(IDL.Text),
  });
  const MealItem = IDL.Record({
    'kcal' : IDL.Nat,
    'name' : IDL.Text,
    'nutrients' : IDL.Text,
  });
  const DietPlan = IDL.Record({
    'date' : IDL.Int,
    'breakfast' : IDL.Vec(MealItem),
    'totalKcal' : IDL.Nat,
    'lunch' : IDL.Vec(MealItem),
    'snacks' : IDL.Vec(MealItem),
    'dinner' : IDL.Vec(MealItem),
  });
  const GameStats = IDL.Record({
    'badges' : IDL.Vec(IDL.Text),
    'longestStreak' : IDL.Nat,
    'healthScore' : IDL.Nat,
    'lastCheckIn' : IDL.Int,
    'currentStreak' : IDL.Nat,
  });
  const SunlightLog = IDL.Record({
    'date' : IDL.Int,
    'uvIndex' : IDL.Nat,
    'recommendation' : IDL.Text,
    'outdoorMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addChatMessage' : IDL.Func([ChatMessage], [], []),
    'addDoctorSuggestions' : IDL.Func([IDL.Vec(DoctorSuggestion)], [], []),
    'addHealthEntry' : IDL.Func([HealthEntry], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func([UserProfile], [], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(AnalysisResult)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChatHistory' : IDL.Func([], [IDL.Vec(ChatMessage)], ['query']),
    'getDietPlan' : IDL.Func([IDL.Int], [IDL.Opt(DietPlan)], ['query']),
    'getDoctorSuggestions' : IDL.Func(
        [],
        [IDL.Vec(DoctorSuggestion)],
        ['query'],
      ),
    'getGameStats' : IDL.Func([], [IDL.Opt(GameStats)], ['query']),
    'getHealthTimeline' : IDL.Func([], [IDL.Vec(HealthEntry)], ['query']),
    'getProfile' : IDL.Func([IDL.Principal], [UserProfile], ['query']),
    'getSunlightHistory' : IDL.Func([], [IDL.Vec(SunlightLog)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'logSunlight' : IDL.Func([SunlightLog], [], []),
    'saveAnalysisResult' : IDL.Func([AnalysisResult], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveDietPlan' : IDL.Func([DietPlan], [], []),
    'updateGameStats' : IDL.Func([GameStats], [], []),
  });
};

export const init = ({ IDL }) => { return []; };