/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalysisResult {
  'moduleName' : string,
  'explanation' : string,
  'timestamp' : bigint,
  'findings' : Array<string>,
  'confidence' : bigint,
  'deficiencies' : Array<string>,
}
export interface ChatMessage {
  'content' : string,
  'role' : string,
  'language' : string,
  'timestamp' : bigint,
}
export interface DietPlan {
  'date' : bigint,
  'breakfast' : Array<MealItem>,
  'totalKcal' : bigint,
  'lunch' : Array<MealItem>,
  'snacks' : Array<MealItem>,
  'dinner' : Array<MealItem>,
}
export interface DoctorSuggestion {
  'name' : string,
  'available' : boolean,
  'specialty' : string,
  'phone' : string,
  'location' : string,
}
export interface GameStats {
  'badges' : Array<string>,
  'longestStreak' : bigint,
  'healthScore' : bigint,
  'lastCheckIn' : bigint,
  'currentStreak' : bigint,
}
export interface HealthEntry {
  'mood' : string,
  'notes' : string,
  'timestamp' : bigint,
  'healthScore' : bigint,
  'vitamins' : Vitamins,
}
export interface MealItem {
  'kcal' : bigint,
  'name' : string,
  'nutrients' : string,
}
export interface SunlightLog {
  'date' : bigint,
  'uvIndex' : bigint,
  'recommendation' : string,
  'outdoorMinutes' : bigint,
}
export interface UserProfile {
  'age' : bigint,
  'region' : string,
  'weight' : bigint,
  'height' : bigint,
  'name' : string,
  'language' : string,
  'dietType' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface Vitamins {
  'b12' : bigint,
  'iron' : bigint,
  'vitC' : bigint,
  'vitD' : bigint,
  'calcium' : bigint,
  'zinc' : bigint,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addChatMessage' : ActorMethod<[ChatMessage], undefined>,
  'addDoctorSuggestions' : ActorMethod<[Array<DoctorSuggestion>], undefined>,
  'addHealthEntry' : ActorMethod<[HealthEntry], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<[UserProfile], undefined>,
  'getAnalysisHistory' : ActorMethod<[], Array<AnalysisResult>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChatHistory' : ActorMethod<[], Array<ChatMessage>>,
  'getDietPlan' : ActorMethod<[bigint], [] | [DietPlan]>,
  'getDoctorSuggestions' : ActorMethod<[], Array<DoctorSuggestion>>,
  'getGameStats' : ActorMethod<[], [] | [GameStats]>,
  'getHealthTimeline' : ActorMethod<[], Array<HealthEntry>>,
  'getProfile' : ActorMethod<[Principal], UserProfile>,
  'getSunlightHistory' : ActorMethod<[], Array<SunlightLog>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'logSunlight' : ActorMethod<[SunlightLog], undefined>,
  'saveAnalysisResult' : ActorMethod<[AnalysisResult], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveDietPlan' : ActorMethod<[DietPlan], undefined>,
  'updateGameStats' : ActorMethod<[GameStats], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];